### ISSUE TITLE
dhcprelya resending its own traffic

### ISSUE THREAD

**Issue by JohnHay** [sem-hub/dhcprelya#4]
If you have a (FreeBSD) router with 2 interfaces and on both interfaces a dhcp pool and a dhcp server with failover configured and dhcprelya on the router with a config like:

[servers]
ip-of-server-on-if1 if2
ip-of-server-on-if2 if1

dhcprelya will get confused because if it sees a dhcp request on if1, it will send it to ip-of-server-on-if2, which is correct, but it then sees that packet it is transmitting on if2 and will send it to ip-of-server-on-if1 as if it originated from if2.

My quick fix was to add " and not ether src " with the MAC to the pcap filter.

[dhcprelya.c.diff.txt](https://github.com/sem-hub/dhcprelya/files/440727/dhcprelya.c.diff.txt)

**Comment by sem-hub** [comment]
Yes, it's make a sense. I will add it. Thanks.
