### ISSUE TITLE
Problem with bind_ip

### ISSUE THREAD

**Issue by maysammortazi** [sem-hub/dhcprelya#5]
Hi, 
I'm using FreeBSD 12.1 amd64
When i use bind_ip to make dhcprelya to bind specified IP address on interface not working.

`# dhcprelya -d -f /usr/local/etc/dhcprelya.conf`
Open server: bind_ip
Can't open server bind_ip. Ignored.
Open server: 192.168.11.112
DHCP server #1: 192.168.11.112
Trying to open interface: eth1
Listen at eth1: 192.168.1.1, 00:90:0b:43:cf:31
Plugin #1 (log) loaded
log_plugin: Detailed: on
log_plugin: Print only incoming: on
Total interfaces: 1

`# cat /usr/local/etc/dhcprelya.conf`
bind_ip eth1 192.168.11.1
[servers]
192.168.11.112 eth1
[log-plugin]
detailed=yes
print_only_incoming=yes

`# ifconfig eth1`
eth1: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=40098<VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,VLAN_HWTSO>
        ether 00:90:0b:43:cf:31
        hwaddr 00:90:0b:43:cf:31
        inet6 fe80::290:bff:fe43:cf31%eth1 prefixlen 64 tentative scopeid 0x2
        inet 192.168.1.1 netmask 0xffffff00 broadcast 192.168.1.255
        inet 192.168.11.1 netmask 0xffffff00 broadcast 192.168.11.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (100baseTX <full-duplex>)
        status: active

**Comment by sem-hub** [comment]
Hello.

bind_ip option must be placed in [server] section only.

**Comment by maysammortazi** [comment]
> 
> 
> Hello.
> 
> bind_ip option must be placed in [server] section only.

I test it but same problem

`# cat /usr/local/etc/dhcprelya.conf`
[servers]
 bind_ip eth1 192.168.11.1
192.168.11.112 eth1
[log-plugin]
detailed=yes
print_only_incoming=yes

**Comment by sem-hub** [comment]
It should work.
But your config is not quite correct. Your DHCP relay listens clients on eth1 and sends requests to server in the same interface. Clients will be answered by DHCP server first for sure. Really you need to listen on one interface and send requests from clients to server on another interface. Your DHCP server will answer to relay requests and the relay will resend the answers to clients on first interface. It's how DHCP relay works.
What do you want to achieve?
