### ISSUE TITLE
request to add 'src port bootpc' to bpf filter

### ISSUE THREAD

**Issue by JohnHay** [sem-hub/dhcprelya#6]
I am using FreeBSD as a router and use dhcprelya on it and that is working fine.

I regularly see this in my syslog messages:
dhcprelya[2290]: length too little -- packet discarded

When I investigated that, I found that NTP packets from external GCNAT servers are causing it. We run a few well-known NTP servers and it looks like the CGNAT servers will use any source port. So I see UDP packets:

request - external-ip src-port 67, internal-ip dst-port 123
reply - internal-ip src-port 123, external-ip dst-port 67

The packets are routed correctly, but the reply packet also gets captured by the dhcprelya bpf filter and cause the message.

I have added 'src port bootpc' and I do not see the messages anymore. I there a reason not to do it?

```
--- dhcprelya.c.orig    2017-12-13 14:18:25.000000000 +0200
+++ dhcprelya.c 2024-09-01 08:42:18.969474000 +0200
@@ -210,7 +210,7 @@
 
        if ((ifs[if_num]->cap = pcap_open_live(iname, max_packet_size, 0, 100, errbuf)) == NULL)
                process_error(EX_RES, "pcap_open_live(%s): %s", iname, errbuf);
-       sprintf(filtstr, "udp and dst port bootps and not ether src %s",
+       sprintf(filtstr, "udp and dst port bootps and src port bootpc and not ether src %s",
                ether_ntoa_r((struct ether_addr*)ifs[if_num]->mac, buf));
        if (pcap_compile(ifs[if_num]->cap, &fp, filtstr, 0, 0) < 0)
                process_error(EX_RES, "pcap_compile");

```

**Comment by sem-hub** [comment]
Looks reasonable. I will commit it soon. Thank you.
